### ISSUE TITLE
Real Time user now showing while adding in Social Engine

### ISSUE THREAD

**Issue by niteshorntech** [cometchat-pro/android-kotlin-chat-app#10]
While adding the user as a friend, the user is not showing in the comet chat users instantly: Real-Time users are not updating
When we are logging out and login in the application again this is showing.

**Comment by darshanbhanushali** [comment]
Hi @niteshorntech ,

Thank you for reporting the issue.
We don't have real-time listeners for getting events while adding & removing friends. We have added this to our feature request. You can track your request by visiting the below link.
https://feedback.cometchat.com/cometchat-pro-feature-requests/p/real-time-event-when-someone-addsremoves-a-friend-via-dashboard-or-api

Also, subscribe to this issue. So you will get notified about updates on this request.

**Comment by niteshorntech** [comment]
Hello Darshan,

So when any user adds any friend this is not showing in comet chat, How we can show that user in comet chat.

**Comment by niteshorntech** [comment]
One thing I figured out about the chat user not showing realtime 
When any person accepts the invitation out of 2 people and if anyone of them does the signout and sign-in again this shows the users for both of them.
I think it may be a quick issue and faced by all of your customers. so please let me know on this on urgent priority as we are a pro customer and paying money for using this and relying on you.

**Comment by darshanbhanushali** [comment]
Hi @niteshorntech ,

Can you share the appId and region of your app?

**Comment by niteshorntech** [comment]
App ID: 166441d1db10ac8
Region: eu

**Comment by adityagokula2210** [comment]
Hello @niteshorntech 
As mentioned, unfortunately, at the moment we do not have this feature available. We have created a feature request on your behalf. You can follow this feature request at:
https://feedback.cometchat.com/cometchat-pro-feature-requests/p/real-time-event-when-someone-addsremoves-a-friend-via-dashboard-or-api

hope this helps.
Thanks
