### ISSUE TITLE
Suggestion: To avoid using findViewById

### ISSUE THREAD

**Issue by yadavmangesh** [cometchat-pro/android-kotlin-chat-app#12]
As the code base is in kotlin you can directly use the view ids instead of writing `findViewById` or make use of `View Binding` if your project is not using `Data Binding`.

@darshanbhanushali @PoojaShivane24

**Comment by proveshapyne** [comment]
Hi @yadavmangesh,

Thank you for your suggestion. I have forwarded this to the team internally and, if applicable, we will make the necessary changes at our end.
Please feel free to write to us at help@cometchat.com if you have any more feedback. 

Regards,
Provesha

**Comment by devedroy** [comment]
Hi @proveshapyne,
I would like to work on this issue.
Can you please assign this to me?
Thanks.

**Comment by randspace0** [comment]
> As the code base is in kotlin you can directly use the view ids instead of writing `findViewById` or make use of `View Binding` if your project is not using `Data Binding`.
> 
> @darshanbhanushali @PoojaShivane24

I think they just convert the Java app to Kotlin instead of "actually writing it" in Kotlin
