### ISSUE TITLE
There are many errors in UIkit-kotlin

### ISSUE THREAD

**Issue by neerajnsp** [cometchat-pro/android-kotlin-chat-app#14]
All R.style inside uikit showing error
implementation 'com.cometchat:pro-android-chat-sdk:3.0.0'
implementation 'com.google.android.material:material:1.6.1'

![Screenshot 2022-08-30 at 7 14 02 PM](https://user-images.githubusercontent.com/65755340/187453266-807164bb-e74f-42de-87aa-6ccb01ec5b90.png)
![Screenshot 2022-09-01 at 11 16 53 AM](https://user-images.githubusercontent.com/65755340/187840655-fee03de5-6890-40e0-bce3-cc89b4217e6f.png)
![Screenshot 2022-09-01 at 11 17 21 AM](https://user-images.githubusercontent.com/65755340/187840707-deb52d05-7807-4287-a2fc-e348fcbb40e9.png)
![Screenshot 2022-09-01 at 11 18 53 AM](https://user-images.githubusercontent.com/65755340/187840907-d69b24ba-9544-4026-9fa2-07a005554ebb.png)
![Screenshot 2022-09-01 at 11 19 09 AM](https://user-images.githubusercontent.com/65755340/187840950-33d53cfd-5580-411f-bcc0-0e51dc9d5742.png)

**Comment by RAJAT2711** [comment]
@neerajnsp Did you get any solution for the above issues? If yes, please share the updated version link.
@darshanbhanushali @PoojaShivane I am facing the same issues, let me know if there is an update.
