### ISSUE TITLE
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:     class okhttp3.logging.HttpLoggingInterceptor, unresolved supertypes: okhttp3.Interceptor

### ISSUE THREAD

**Issue by abhi-9605** [cometchat-pro/android-kotlin-chat-app#4]
implementation 'com.squareup.retrofit2:converter-gson:2.4.0'
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.11.0'
    implementation 'com.squareup.okhttp3:okhttp:3.11.0'

 implementation('com.cometchat:pro-android-chat-sdk:1.8.8') {
        configurations {
            compile.exclude module: 'gson'
            compile.exclude module: 'okhttp'
            compile.exclude module: 'okhttp3'
        }
    }

**Comment by Abhikumarm** [comment]
implementation('com.cometchat:pro-android-chat-sdk:1.8.0') {
        exclude group: 'com.squareup.okio'
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
        exclude group: 'com.google.code.gson', module: 'gson'
    }

**Comment by abhi-9605** [comment]
Hi please check these also when I use comet-chat-pro and retrofit together

**Comment by yadavmangesh** [comment]
@Abhikumarm  
Thank you for reporting we'll look into it and get back to you ASAP

**Comment by yadavmangesh** [comment]
@Abhikumarm  
Can you please try excluding the dependencies this way 
```
implementation('com.cometchat:pro-android-chat-sdk:1.8.8') {
        exclude group: 'com.squareup.okio'
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
        exclude group: 'com.google.code.gson', module: 'gson'
    }
```
