### ISSUE TITLE
Group Video calling issue

### ISSUE THREAD

**Issue by chiragnahartops** [cometchat-pro/android-kotlin-chat-app#5]
I have an issue in group video calling when i call in group more than 2 user that time i can't see other user video streaming it showing only other user profile picture so please check this

**Comment by darshanbhanushali** [comment]
Hi @chiragdabhi0007 Thanks for reporting the issue. We will resolve this issue in our upcoming release. You can watch this issue for updates.

**Comment by darshanbhanushali** [comment]
Hi,

We have updated our sample app with the latest SDK v2.1.0 which has a completely new Calling module in place. Please upgrade to the latest version and provide us with your feedback.
Also, check the latest docs which include more details for a new calling module.
https://prodocs.cometchat.com/docs/android-calling
