### ISSUE TITLE
Default User Last Login Time Wrong

### ISSUE THREAD

**Issue by niteshorntech** [cometchat-pro/android-kotlin-chat-app#9]
When adding new user, default online date shows of: 01.01/1970 if the user not logged for a single time

**Comment by darshanbhanushali** [comment]
Hi @niteshorntech ,

It's default value of `lastActiveAt` whenever you create a user. If you not need to show it, then you can hide it using the below condition.
```
if(user.getLastActiveAt()==0) { 
\\Your Code to hide
}
```
